### ISSUE TITLE
"Donate Now" suggests huge transaction after changing separator characters.

### ISSUE THREAD

**Issue by lkamp** [bitcoin-solutions/multibit-hd#444]
I am using MultiBit in Europe and changed my "Units" settings to use '.' as the grouping separator and ',' as the decimal separator. The dialog that pops up after clicking "Preferences" > "Fees" > "Donate now" seems to have the hardcoded string "10.00000" in the amount field. This suggests a donation amount of one thousand BTC with the changed separator settings. I suppose this is not intended ;-)

**Comment by jim618** [comment]
That would be quite a generous donation yes ! :-)
We missed that yes - it is hardcoded rather than localised.

**Comment by gary-rowe** [comment]
The problem was in the `EnterAmountView` using the BigDecimal plain string formatting rather than respecting the current configuration. This has now been fixed with a few unit tests to cover it.

Ready for review and close.

**Comment by jim618** [comment]
Not fixed.
Just did a pull and saw updates to FeeService, Formats, EnterAmountView, FormatsTest.
Did the following:
1) With decimal separator at . went into Fees, clicked donate. Saw correct amount
2) Went into units, set decimal separator to be , and grouping separator to be . Went into Fees, clicked donate. Saw amount too big. Screenshot:

![screen shot 2015-03-10 at 10 33 59](https://cloud.githubusercontent.com/assets/919427/6573288/59a16892-c711-11e4-8f55-18968a89eca8.png)

**Comment by gary-rowe** [comment]
Here's where the problem most likely lies: https://github.com/bitcoin-solutions/multibit-hd/blob/f484b824a0564705aafa481cc4fcb860e75d2384/mbhd-swing/src/main/java/org/multibit/hd/ui/views/components/enter_amount/EnterAmountView.java#L314

Within the `.setValue()` call is a sneaky default formatter that doesn't use the `Configuration`. It's one that will either be a quick fix, or could turn into something more complex.

**Comment by gary-rowe** [comment]
I've tried replicating this but cannot - even after various combinations and permutations of Unit and Exchange settings. I click the Donate button and see the following:

![screen shot 2015-03-10 at 21 59 40](https://cloud.githubusercontent.com/assets/342133/6586367/d1b5177a-c770-11e4-9cc1-7c136942ae4c.png)

The 0.01 BTC in the Bitcoin URI gets converted into "10,00000" mBTC based on the grouping separator being "." and the decimal separator being "," (Euro style). 

The only way I could replicate what you've seen was by typing in "10.0" which triggered the x100 increase due to the formatter treating it as "10,000" (UK style). Could you verify this once again just in case?

**Comment by jim618** [comment]
I cannot reproduce the screenshot I posted before - it all works as expected.
I see 10,00000 mBTC with a euro-style separator.

Closing
