### ISSUE TITLE
new Trezor wallet is over syncing

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#545]
I just created a new Trezor wallet and it started syncing from the 'HD wallet birthday'. This is 50K+ blocks.
For a new wallet it does not have to do this as it won't have any tx.

It could just sync from the last checkpoint, like a new soft wallet.

**Comment by jim618** [comment]
On coffee shop wifi the sync takes 5 to 10 minutes so it's not a disaster but would be a nice improvement

**Comment by gary-rowe** [comment]
I've seen this too with a fresh hard wallet. Even though the timing isn't too onerous (today) it gives the bad impression that we've dropped some data along the way and forgotten that we just made this wallet.

**Comment by jim618** [comment]
I have updated the code - we remember the 'last wallet created' label and a time but it wasn't being persisted at the right point. Fixed.

To test it create a wallet on a blank Trezor wallet. It should sync from the last checkpoint, typically in a minute or so.

Awaiting review and closing

**Comment by gary-rowe** [comment]
Still seeing sync from 57K blocks. This was from a wiped Trezor after 2 minutes:

![screen shot 2015-05-10 at 18 37 59](https://cloud.githubusercontent.com/assets/342133/7555450/da6423b8-f743-11e4-9faa-6d5bc88442bf.png)

The process was:

* Unlock Trezor, Tools | Wipe, Switch
* Create wallet
* Unlock

I think we're still dropping the wallet creation date somewhere.

**Comment by jim618** [comment]
I have simplified the code that stored the 'recentData' in the yaml (for a new Trezor wallet).
Tested successfully in the scenario above to check that syncing is done from the last checkpoint (as per a regular new soft wallet).

Awaiting retest and closing

**Comment by gary-rowe** [comment]
Another fail unfortunately. I went through the same process as before (Tools | Wipe then Switch then Create). Here's the log:

```
[2015-05-13 19:54:51,885] DEBUG [safe-fixed-unlock-wallet-0] o.m.h.c.m.WalletManager - The blockStore is at height 344736 
[2015-05-13 19:54:51,886] DEBUG [safe-fixed-unlock-wallet-0] o.m.h.c.m.WalletManager - Syncing wallet from date 2014-05-01T00:00:00.000+01:00 
[2015-05-13 19:54:51,886] DEBUG [safe-fixed-unlock-wallet-0] o.m.h.c.m.WalletManager - Synchronise wallet called with syncDate Optional.of(Thu May 01 00:00:00 BST 2014) 
[2015-05-13 19:54:51,886] DEBUG [safe-fixed-sync-wallet-0] o.m.h.c.m.WalletManager - synchroniseWallet  called with replay date Optional.of(Thu May 01 00:00:00 BST 2014) 
[2015-05-13 19:54:51,886] DEBUG [safe-fixed-sync-wallet-0] o.m.h.c.s.BitcoinNetworkService - Stopping any existing downloads 
[2015-05-13 19:54:51,886] DEBUG [safe-fixed-sync-wallet-0] o.m.h.c.s.BitcoinNetworkService - Peer group was not present 
[2015-05-13 19:54:51,886] DEBUG [safe-fixed-sync-wallet-0] o.m.h.c.s.BitcoinNetworkService - blockStore was not present 
[2015-05-13 19:54:51,887] INFO  [safe-fixed-sync-wallet-0] o.m.h.c.s.BitcoinNetworkService - Starting replay of wallet with id '9ad044c6-37d4aba1-cf174c69-696b2c19-02cad647' from date Optional.of(Thu May 01 00:00:00 BST 2014) 
[2015-05-13 19:54:51,887] DEBUG [safe-fixed-sync-wallet-0] o.m.h.c.s.BitcoinNetworkService - Recreating blockstore with checkpoint date of Optional.of(Thu May 01 00:00:00 BST 2014) ... 
[2015-05-13 19:54:51,887] DEBUG [safe-fixed-sync-wallet-0] o.m.h.c.f.SecureFiles - Verify or create file:
'/Users/garyrowe/Library/Application Support/MultiBitHD/mbhd-9ad044c6-37d4aba1-cf174c69-696b2c19-02cad647/mbhd.spvchain' 
[2015-05-13 19:54:51,887] DEBUG [safe-fixed-sync-wallet-0] o.m.h.c.f.SecureFiles - Verify or create file:
'/Users/garyrowe/Library/Application Support/MultiBitHD/mbhd-9ad044c6-37d4aba1-cf174c69-696b2c19-02cad647/mbhd.checkpoints' 
[2015-05-13 19:54:52,108] DEBUG [safe-fixed-sync-wallet-0] o.m.h.c.m.BlockStoreManager - Deleting SPV block store (pass 1) from file:
'/Users/garyrowe/Library/Application Support/MultiBitHD/mbhd-9ad044c6-37d4aba1-cf174c69-696b2c19-02cad647/mbhd.spvchain' 
[2015-05-13 19:54:52,108] DEBUG [safe-fixed-sync-wallet-0] o.m.h.c.m.BlockStoreManager - isWritable: 'true' isDeletedOK: 'true' 
[2015-05-13 19:54:52,108] DEBUG [safe-fixed-sync-wallet-0] o.m.h.c.m.BlockStoreManager - Get or create SPV block store (pass 1):
'/Users/garyrowe/Library/Application Support/MultiBitHD/mbhd-9ad044c6-37d4aba1-cf174c69-696b2c19-02cad647/mbhd.spvchain' 
[2015-05-13 19:54:52,109] DEBUG [safe-fixed-sync-wallet-0] o.m.h.c.m.BlockStoreManager - Block store in place. Created new: true 
[2015-05-13 19:54:52,109] DEBUG [safe-fixed-sync-wallet-0] o.m.h.c.m.BlockStoreManager - Checkpoints exist attempting to stream from:
'/Users/garyrowe/Library/Application Support/MultiBitHD/mbhd-9ad044c6-37d4aba1-cf174c69-696b2c19-02cad647/mbhd.checkpoints' 
[2015-05-13 19:54:52,112] DEBUG [safe-fixed-sync-wallet-0] o.m.h.c.s.BitcoinNetworkService - Blockstore is 'org.bitcoinj.store.SPVBlockStore@7a08334c' 
[2015-05-13 19:54:52,112] DEBUG [safe-fixed-sync-wallet-0] o.m.h.c.s.BitcoinNetworkService - Peer group was not present 
[2015-05-13 19:54:52,113] DEBUG [safe-fixed-sync-wallet-0] o.m.h.c.s.BitcoinNetworkService - Creating block chain from blockStore org.bitcoinj.store.SPVBlockStore@7a08334c... 
[2015-05-13 19:54:52,113] WARN  [safe-fixed-sync-wallet-0] o.b.c.AbstractBlockChain - Wallet/chain height mismatch: 0 vs 296352 
[2015-05-13 19:54:52,113] WARN  [safe-fixed-sync-wallet-0] o.b.c.AbstractBlockChain - Hashes: null vs 00000000000000003decdbb5f3811eab3148fbc29d3610528eb3b50d9ee5723f 
[2015-05-13 19:54:52,113] DEBUG [safe-fixed-sync-wallet-0] o.m.h.c.s.BitcoinNetworkService - Created block chain 'org.bitcoinj.core.BlockChain@3060012b' with height '296352' 
[2015-05-13 19:54:52,113] DEBUG [safe-fixed-sync-wallet-0] o.m.h.c.s.BitcoinNetworkService - Creating peer group with useFastCatchup: true ... 
[2015-05-13 19:54:52,113] INFO  [safe-fixed-sync-wallet-0] o.m.h.c.s.BitcoinNetworkService - Creating new DNS peer group for 'org.bitcoinj.params.MainNetParams@9d1d82f2' 
[2015-05-13 19:54:52,115] DEBUG [safe-fixed-sync-wallet-0] o.m.h.c.s.BitcoinNetworkService - Created peer group 'org.bitcoinj.core.PeerGroup@176521f0' 
[2015-05-13 19:54:52,115] DEBUG [safe-fixed-sync-wallet-0] o.m.h.c.s.BitcoinNetworkService - Starting peer group ... 
[2015-05-13 19:54:52,115] DEBUG [safe-fixed-sync-wallet-0] o.m.h.c.s.BitcoinNetworkService - Started peer group. 
[2015-05-13 19:54:52,117] DEBUG [safe-fixed-sync-wallet-0] o.m.h.c.s.BitcoinNetworkService - Blockchain download started. 
[2015-05-13 19:54:52,117] DEBUG [safe-fixed-sync-wallet-0] o.m.h.c.m.WalletManager - Sync has begun 
[2015-05-13 19:54:52,117] DEBUG [safe-fixed-bitcoin-network-0] o.m.h.c.s.BitcoinNetworkService - Recalculating bloom filter ... 
[2015-05-13 19:54:52,119] DEBUG [safe-fixed-bitcoin-network-0] o.m.h.c.s.BitcoinNetworkService - Downloading block chain... 
[2015-05-13 19:54:52,119] DEBUG [safe-fixed-bitcoin-network-0] o.m.h.c.s.BitcoinNetworkService - Starting blockchain download . . . 
[2015-05-13 19:55:15,249] WARN  [PeerGroup Thread] o.b.c.PeerGroup - Chain download stalled: received 1.25 KB/sec for 10 seconds, require average of 1.56 KB/sec, disconnecting [144.76.183.77]:8333 
[2015-05-13 19:55:15,250] INFO  [bitcoinj user thread] o.m.h.c.n.MultiBitPeerEventListener - Started download with 59938 blocks to download 
[2015-05-13 19:55:20,629] WARN  [NioClientManager] o.b.c.AbstractBlockChain - Block does not connect: 000000000000000010a33052fca14166bde756df88e4ff1091e2bd4e4259b014 prev 00000000000000000a7391e98680206ef8d17f705d64771a43f4f3316b8e9983 
```
Note that it wants to sync from **2014**-05-01T00:00:00Z not 2015-05-13 as expected.

**Comment by jim618** [comment]
I just retested this and it only synced 10K blocks.

The steps I am taking are:
1) Plug in a Trezor. (This had a wallet and some bitcoin on so I emptied it with an Empty wallet)
2) Tools | Trezor | Wipe Trezor
3) Switch wallet
4) Leading to 'Create new Trezor wallet'.
5) This all ran through and synced ok.

I think you will have to debug it on your machine as I cannot replicate it.
The easiest way to debug is to breakpoint:
WalletConfiguration#getRecentWalletDataValidity
WalletConfiguration#setRecentWalletDataValidity
WalletConfiguration#getRecentWalletLabel
WalletConfiguration#setRecentWalletLabel

When the Trezor create wallet completes, these fields are set.
Then when the wallet is read in from disk and opened they are used to determine the sync date.

You can see the fields in the YAML. In fact it is critical the YAML is saved otherwise they are lost.



The steps I am taking are:
1) Plug in a Trezor. (This had a wallet and some bitcoin on so I emptied it with an Empty wallet)
2) Tools | Trezor | Wipe Trezor
3) Switch wallet
4) Leading to 'Create new Trezor wallet'.
5) This all ran through and synced ok.

I think you will have to debug it on your machine as I cannot replicate it.
The easiest way to debug is to breakpoint:
WalletConfiguration#getRecentWalletDataValidity
WalletConfiguration#setRecentWalletDataValidity
WalletConfiguration#getRecentWalletLabel
WalletConfiguration#setRecentWalletLabel

When the Trezor create wallet completes, these fields are set.
Then when the wallet is read in from disk and opened they are used to determine the sync date.

You can see the fields in the YAML. In fact it is critical the YAML is saved otherwise they are lost.

**Comment by gary-rowe** [comment]
Made various adjustments to the sync replay date calculation code. The only logic change is replacing the check for != -1 with >=0 for detecting epoch from wallets without ECKeys containing timestamps. 

A few things to take a look at during code review:
* new replay date calculation method in `WalletManager` (worth close inspection)
* `Date` becomes `DateTime` throughout replay API for consistency
* Reduced/improved logging in places
* Improved documentation

In general it might be worth @jim618 looking over callers of `BitcoinNetworkService.replayWallet()` to ensure that their flags are correct (e.g. some have no mempool clearing etc)

Since making these changes I've not seen a repeat of the long sync over 20 or so wallet wipe/create operations (before it was every time) so I'm marking this as ready for review and close.

**Comment by jim618** [comment]
Reviewed the code and it looks fine.
Synced / repaired various wallets, created new soft and hard wallets and everything works as expected.

Closing.
