### ISSUE TITLE
CrashReporter: Change language to german on cold start crashes MBHD

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#586]
If you do the following you get the CrashReporter:

+ Cold start
+ Accept licence
+ Change language to German

Stack trace:
```
{"@timestamp":"2015-06-02T21:50:55.351+01:00","@version":1,"message":"Populating view map and firing initial state view events...","logger_name":"org.multibit.hd.ui.views.wizards.AbstractWizard","thread_name":"AWT-EventQueue-0","level":"DEBUG","level_value":10000}
{"@timestamp":"2015-06-02T21:50:56.301+01:00","@version":1,"message":"Showing wizard panel: WELCOME_SELECT_LANGUAGE","logger_name":"org.multibit.hd.ui.views.wizards.AbstractWizard","thread_name":"AWT-EventQueue-0","level":"DEBUG","level_value":10000}
{"@timestamp":"2015-06-02T21:50:56.302+01:00","@version":1,"message":"Show light box","logger_name":"org.multibit.hd.ui.views.components.Panels","thread_name":"AWT-EventQueue-0","level":"DEBUG","level_value":10000}
{"@timestamp":"2015-06-02T21:50:56.312+01:00","@version":1,"message":"Uncaught exception","logger_name":"org.multibit.hd.core.error_reporting.ExceptionHandler","thread_name":"AWT-EventQueue-0","level":"ERROR","level_value":40000,"stack_trace":"java.lang.IllegalStateException: Light box should never be called twice \n\tat 
SNIP
com.google.common.base.Preconditions.checkState(Preconditions.java:176) ~[multibit-hd.jar:na]\n\tat org.multibit.hd.ui.views.components.Panels.showLightBox(Panels.java:253) ~[multibit-hd.jar:na]\n\tat org.multibit.hd.ui.views.MainView.refreshOnEventThread(MainView.java:260) ~[multibit-hd.jar:na]\n\tat org.multibit.hd.ui.views.MainView.refresh(MainView.java:179) ~[multibit-hd.jar:na]\n\tat org.multibit.hd.ui.controllers.MainController$6.run(MainController.java:764) ~[multibit-hd.jar:na]\n\tat 
{"@timestamp":"2015-06-02T21:50:56.323+01:00","@version":1,"message":"Hide light box (if present)","logger_name":"org.multibit.hd.ui.views.components.Panels","thread_name":"AWT-EventQueue-0","level":"DEBUG","level_value":10000}
{"@timestamp":"2015-06-02T21:50:56.323+01:00","@version":1,"message":"Hide light box popover (if present)","logger_name":"org.multibit.hd.ui.views.components.Panels","thread_name":"AWT-EventQueue-0","level":"DEBUG","level_value":10000}
{"@timestamp":"2015-06-02T21:50:56.323+01:00","@version":1,"message":"[0]: JPanel","logger_name":"org.multibit.hd.ui.views.components.panels.LightBoxPanel","thread_name":"AWT-EventQueue-0","level":"DEBUG","level_value":10000}
{"@timestamp":"2015-06-02T21:50:56.323+01:00","@version":1,"message":"[1]: LightBoxPanel","logger_name":"org.multibit.hd.ui.views.components.panels.LightBoxPanel","thread_name":"AWT-EventQueue-0","level":"DEBUG","level_value":10000}
{"@timestamp":"2015-06-02T21:50:56.323+01:00","@version":1,"message":"[2]: JPanel","logger_name":"org.multibit.hd.ui.views.components.panels.LightBoxPanel","thread_name":"AWT-EventQueue-0","level":"DEBUG","level_value":10000}
{"@timestamp":"2015-06-02T21:50:56.329+01:00","@version":1,"message":"Wizard light box panel removed from application frame","logger_name":"org.multibit.hd.ui.views.components.panels.LightBoxPanel","thread_name":"AWT-EventQueue-0","level":"DEBUG","level_value":10000}
```

**Comment by jim618** [comment]
I think this is related to the view refresh _of the language screen_ that MBHD tries to do when you select the language.
Perhaps KISS and remove this, just changing the language when the next is selected.

**Comment by gary-rowe** [comment]
I've pushed some changes to enforce the disabling of the language drop down. This was allowing multiple click events to overlap which was causing one light box to be drawn over another. After adding this I couldn't get a failure with the mouse (previously I could with some impatient clickety-click). 

Repeating the same impatience with the keyboard did (after some effort) yield a failure so I added a short delay in the welcome wizard startup to allow for the deferred hide to complete. A language change is a rare event normally so I think this is OK, but for a real solution we should use a Future in the ViewEvents to allow visibility from waiting processes that the light box has closed (or is in the process of closing).

Ready for review and close.

**Comment by jim618** [comment]
The push above still wasn't resilient enough - still seeing the 'two lightboxes' problem.
This code is quite racey.
In the end the only way I could get it to work reliably was to:
+ close down the existing lightbox
+ wait
+ fire up the new one

This makes the wizard disappear for a second or so which doesn't look great but it works reliably even if you are clickety-click-keyboard-pressity-press

When checking pay particular attention to the enter key as that broke the previous code.
Awaiting review and closing.

**Comment by gary-rowe** [comment]
Could you perform a `git commit --ament -m "#586 something"` to ensure the issue number is against your most recent commit, please?

**Comment by gary-rowe** [comment]
Had some confusion about where to go with this as it seems there is no push of code as implied by the "awaiting review". I really don't like the idea of the wizard vanishing for a second - it gives a terrible first impression.

I think this warrants a bit of extra effort to introduce a `Future` that a light box can use to make a better decision about rendering the next one. Leave it with me for a bit.

**Comment by jim618** [comment]
@gary-rowe sorry - missed that my push failed because you'd made a change.
I've pushed it now (though you'll probably want to change it)
I'll leave the code to you now for a bit

**Comment by gary-rowe** [comment]
I've taken a more lightweight approach than a `Future` in the hope that it will involve the least number of code changes. 

This commit provides a simple deferred flag in `Panels` that will case a new light box to be executed after all other AWT events that have been stacked up. Can you take a look at it and see if it a) fixes the problem, b) provides a more general "defer point" than the more targeted approach you pushed earlier (which I've removed in anticipation of this being cleaner).

**Comment by jim618** [comment]
Looks good.
Closing
